# Generated by Django 3.1.3 on 2020-12-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201210_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=1, max_length=25, verbose_name='firstname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=1, max_length=25, verbose_name='lastname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
