# Generated by Django 3.1.3 on 2020-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201218_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
