# Generated by Django 3.1.3 on 2020-12-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201219_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=253, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=254, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
