# Generated by Django 3.1.3 on 2020-12-22 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201219_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(editable=False, max_length=72, null=True, unique=True),
        ),
    ]
