# Generated by Django 3.1.3 on 2020-12-10 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_address', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('balance', models.CharField(default=0, editable=False, max_length=15)),
                ('currency_type', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Fortron', 'Fortron'), ('Ethereum', 'Ethereum'), ('Litecoin', 'Litecoin')], default='Bitcoin', max_length=25)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
