# Generated by Django 3.1.3 on 2020-12-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201210_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(default=0, editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency_type',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Fortron', 'Fortron'), ('Ethereum', 'Ethereum'), ('Litecoin', 'Litecoin')], default='Bitcoin', max_length=25),
        ),
    ]
