# Generated by Django 3.1.4 on 2021-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210110_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
