# Generated by Django 3.1.3 on 2020-12-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='payclaim',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
