# Generated by Django 3.1.4 on 2021-01-12 21:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210112_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authpin',
            name='id',
        ),
        migrations.AlterField(
            model_name='authpin',
            name='pin',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='authpin',
            name='withdraw_request',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqs', to='main.withdrawalrequest'),
        ),
    ]
