# Generated by Django 3.1.3 on 2020-12-22 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payclaim_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currency_type',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
