# Generated by Django 3.1.4 on 2021-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201222_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payclaim',
            name='curr',
            field=models.CharField(max_length=25, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='payclaim',
            name='sender_addr',
            field=models.CharField(max_length=64, verbose_name='Sending Wallet Address'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
