# Generated by Django 3.1.4 on 2021-01-12 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210112_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authpin',
            name='pin',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=72, primary_key=True, serialize=False, unique=True),
        ),
    ]
