# Generated by Django 3.1.4 on 2021-01-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210109_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
